apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env: # tu moramo dodati novo env spremenljivko.
    - name: myusername # poimenujemo jo.
      valueFrom:
        secretKeyRef:
          name: secret-demo # ime secreta, ki smo ga prej kreirali (bodisi iz yaml fajla, kubectl, ali iz user:pass fajlov)
          key: username # v našem secret-demo imamo dve vrednosti. Torej username in password. Tu iz tega secreta vzamemo samo username. 
