apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes: # nareimo volume
  - name: secret-volume # volume poimenujemo. 
    secret: # tip voluma bo secret.
      secretName: secret-demo # ime našega secreta, ki smo ga prej kreirali.
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: secret-volume # to ime se mora ujemati z imenom voluma zgoraj v fajlu.
      mountPath: /mydata # tu bomo mountali naš volume. Če bomo šli v to mapo v containerju, bomo znotraj imeli 1 file na key/value pair iz našega secret resursa.
