apiVersion: v1
kind: Secret # Kind je pač secret.
metadata:
  name: secret-demo # ime secreta.
type: Opaque
data:
  username: a3ViZWFkbWlu # username enkriptiran z base64. V notepadu je opisano, kako dobimo enkriptirano vrednost.
  password: cmFuZG9tcGFzc3dvcmQ= # Nov password enkriptiran z base64. V notepadu je opisano, kako dobimo enkriptirano vrednost.
  name: RHJhZ2Fu # novo dodan key/pair value "name".
