apiVersion: storage.k8s.io/v1
kind: StorageClass # tip resursa je storageclass
metadata:
  name: managed-nfs-storage # ime storageclassa. Vsakič ko delamo PVC moramo referirati na ta storageclass. Druače se persistent volume ne bo provisioniral. 
provisioner: example.com/nfs # to je samo ime provisionerja
parameters:
  archiveOnDelete: "false"
