apiVersion: v1
kind: PersistentVolumeClaim # Kind je PVC
metadata:
  name: pvc1 # Ime PVCja
spec:
  storageClassName: managed-nfs-storage # zelo pomembno, da se ime ujema z imenom, ki smo ga dali storageclassu. Lahko preveriš s "kubectl get storageclass".
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi # Zahtevamo 500MB.