apiVersion: v1
kind: ResourceQuota # Kreirali bomo resource quoto.
metadata:
  name: quota-demo1 # tako bo ime quote.
  namespace: quota-demo-ns # pripadala bo temu namespacu.
spec:
  hard:
    pods: "2" # v tem namespacu ne sme biti več kot 2 poda.
    configmaps: "1" # v tem namespacu ne sme biti več kot en configmap.
