apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: quota-demo-ns
spec:
  containers:
  - image: nginx
    name: nginx
    resources: 
     limits:
       memory: "200Mi" #Specificiramo 200MB RAMa na ta POD.

