apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Updated to latest version." # Dodamo novo vrstico, kjer damo annotation že kar v yaml fajl.
  labels:
    run: nginx
  name: nginx-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      run: nginx
  strategy: # Za rolling update smo dodali cel "Strategy" element, minReadySeconds in revisionHistoryLimit.
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 2 # Spremenimo v 2, da pohitrimo update.
      maxUnavailable: 2
  minReadySeconds: 5
  revisionHistoryLimit: 2 # Za test spremenimo Revision History.
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:latest # To vrednost bomo spreminjali
        name: nginx
