apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Updated to latest version." # Dodamo novo vrstico, kjer damo annotation že kar v yaml fajl.
  labels:
    run: nginx
  name: nginx-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      run: nginx
  strategy: # Za rolling update smo dodali cel "Strategy" element, minReadySeconds in revisionHistoryLimit.
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 0 # # Če imamo max surge nastavljeno na 0, potem ne smemo imeti max unavailable nastavljeno na 0. Druače ne moremo updatati.
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:1.14 # To vrednost bomo spreminjali
        name: nginx
