apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env: # Tu definiramo dve ENv variabli, CHANNELNAME in CHANNELOWNER.
    - name: CHANNELNAME
      valueFrom: # Od kje bomo dobili vrednost teh spremenljivk?
        configMapKeyRef: # Dobili bomo iz ConfigMap Key.
          name: demo-configmap # ime prej kreiranega config mapa.
          key: channel.name # Key znotraj tega ConfigMapa.
    - name: CHANNELOWNER # Enako kot pri spremenljivki CHANNELNAME.
      valueFrom:
        configMapKeyRef:
          name: demo-configmap
          key: channel.owner
