apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes: # definiramo volume
  - name: demo # z imenom demo
    configMap: # volume pride iz confi mapa
      name: demo-configmap # volume bo prišel iz config mapa s tem imenom
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: demo # volume mountamo znotraj containerja. Ime se mora ujemati z zgornjim definiranim imenom.
      mountPath: /mydata # mapa znotraj containerja, kjer bo mount.
