apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes: # ustvarimo volume
  - name: mysql-config # ime voluma
    configMap: # Uporabimo configmap.
      name: mysql-demo-config # Ime configmapa.
      items: #Znotraj containerja želim kreirati configuration fajl.
        - key: my.cnf # ključ je my.cnf.
          path: my.cnf # path variabla bo my.cnf
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: mysql-config # poskrbimo, da ima volume, ki ga mountamo, isto ime kot volume, ki smo ga kreirali. 
      mountPath: /mydata # folder v katerega volume mountamo.
